# Permalinks
permalink:        pretty

# Setup
title:            m&#39;s blog
tagline:          'We&#39;re all different. This is the only thing we have in common.'
description:      'practical thoughts about software engineering'
url:              https://ludovicianul.github.io/
baseurl:          https://ludovicianul.github.io/

author:
  name:           'Madalin Ilie'
  url:            https://twitter.com/ludovicianul

paginate:         5

google_analytics: G-P3LSHCBCB5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ludovicianul
